## creating dataframes

### 1. Option 1 (numpy)

In [2]:
import numpy as np
import pandas as pd

In [4]:
# creating array
data = np.array([[1,2],[3,4],[5,6],[7,8]])

In [5]:
# creating dataframe
df = pd.DataFrame(data,index=["row1","row2","row3","row4"], columns=["col1","col2"])
print(df)

      col1  col2
row1     1     2
row2     3     4
row3     5     6
row4     7     8

### 1.2 Option 2 (Lists)

In [6]:
# creating an array with list

data2 = [[1,2],[3,4],[5,6]]

In [7]:
df = pd.DataFrame(data2,index=["row1","row2","row3"],columns=["col1","col2"])
df

      col1  col2
row1     1     2
row2     3     4
row3     5     6

### 2. Dictionary

In [8]:
states = ["California","Texas","Florida","New york"]
population=[3242342,345345345,234234,6446456]

In [9]:
dict_States = {"States":states,"Population":population}

In [10]:
df = pd.DataFrame(dict_States)

In [11]:
df

       States  Population
0  California     3242342
1       Texas   345345345
2     Florida      234234
3    New york     6446456

### 3. CSV file

In [12]:
df_exams = pd.read_csv("StudentsPerformance.csv")

In [13]:
df_exams

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

In [14]:
# showing first 10 rows
df_exams.head(10)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
5,female,group B,associate's degree,standard,none,71,83,78
6,female,group B,some college,standard,completed,88,95,92
7,male,group B,some college,free/reduced,none,40,43,39
8,male,group D,high school,free/reduced,completed,64,64,67
9,female,group B,high school,free/reduced,none,38,60,50

In [12]:
# showing last 5 rows
# showing last 10 rows
df_exams.tail(10)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
990,male,group E,high school,free/reduced,completed,86,81,75
991,female,group B,some high school,standard,completed,65,82,78
992,female,group D,associate's degree,free/reduced,none,55,76,76
993,female,group D,bachelor's degree,free/reduced,none,62,72,74
994,male,group A,high school,standard,none,63,63,62
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

In [15]:
# shape attribute

df_exams.shape

(1000, 8)

In [ ]:
# how many rows to display

pd.set_option("display.max_rows",100)

In [ ]:
df_exams

In [15]:
df_exams.head(100)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
...,...,...,...,...,...,...,...,...
95,male,group C,associate's degree,free/reduced,completed,78,81,82
96,male,group B,some high school,standard,completed,65,66,62
97,female,group E,some college,standard,completed,63,72,70
98,female,group D,some college,free/reduced,none,58,67,62
99,female,group D,bachelor's degree,standard,none,65,67,62